### ISSUE TITLE
more data in hearings endpoints

### ISSUE THREAD

**Issue by sckott** [rOpenGov/rsunlight#36]
https://sunlightlabs.github.io/congress/hearings.html

**Comment by sorensje** [comment]
Hi! 

I love the project, I was actually thinking of trying to create something like this. I'm new to collaborating on github, so please excuse me if I mess up any etiquette.  It looks like in this request, you just need to update some args in R/cg_hearings to reflect changes in the Sunlight API.  Mind if I take a crack at it?

**Comment by sckott** [comment]
@sorensje Please do. I can't remember exactly what I meant by _more data_, but please do see what can be updated/added/etc.  

Please do fork the repo, make a branch, make your changes, then submit a pull request to this master branch  - thanks :)

**Comment by sorensje** [comment]
It looks like there have been a few fields added to the sunlight hearings endpoint. However, they aren't fields that can be used to filter results, and as it's written now, cg_hearings returns the values of these fields, so I didn't add them to the cg_hearings as args. 

I added some documentation to the cg_hearings() function however, and changed the date input from numeric to character (in order to filter on that field, you must provide a data in the format "2014-05-21T13:00:00Z") .

**Comment by sckott** [comment]
thanks!

**Comment by sckott** [comment]
i think that's it, closing
